// <auto-generated />
namespace Locadora.infraestrutura.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class arrumandoIdsTabelaLocacao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(arrumandoIdsTabelaLocacao));
        
        string IMigrationMetadata.Id
        {
            get { return "201706072011184_arrumandoIdsTabelaLocacao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
