// <auto-generated />
namespace Locadora.infraestrutura.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adicionarColunaValorTotalNaLocacao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adicionarColunaValorTotalNaLocacao));
        
        string IMigrationMetadata.Id
        {
            get { return "201706081503552_adicionarColunaValorTotalNaLocacao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
